In [1]:
!pip install kaggle

Collecting kaggle
  Downloading kaggle-1.7.4.5-py3-none-any.whl.metadata (16 kB)
Collecting bleach (from kaggle)
  Downloading bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: certifi>=14.05.14 in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (2023.5.7)
Requirement already satisfied: charset-normalizer in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (3.1.0)
Requirement already satisfied: idna in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (3.4)
Requirement already satisfied: protobuf in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (4.25.4)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (2.8.2)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: requests in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (2.30.0)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (65.5.0)
Requirement already satisfied: six>=1.10 in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (1.16.0)
Collecting text-unidecode (from kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: tqdm in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from kaggle) (1.26.15)
Collecting webencodings (from kaggle)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: colorama in c:\users\prema\appdata\local\programs\python\python310\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-1.7.4.5-py3-none-any.whl (181 kB)
Downloading bleach-6.2.0-py3-none-any.whl (163 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, text-unidecode, python-slugify, bleach, kaggle
Successfully installed bleach-6.2.0 kaggle-1.7.4.5 python-slugify-8.0.4 text-unidecode-1.3 webencodings-0.5.1

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import kaggle

In [9]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv to d:\Data analytics\python\Analytics Prj

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|██████████| 200k/200k [00:00<00:00, 203MB/s]

In [10]:
#dont wanna use this .. it's alredy extracted
import zipfile as zip 
zip_reffer = zip.ZipFile('archive.zip')   #Creating OBJ
zip_reffer.extractall()                      #using the Obj to extract all ("we can also give path")
zip_reffer.close()                           #Closing the obj

In [2]:
import pandas as pd
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])

In [3]:
df['Ship Mode'].unique()    #gives unique, Distinct Value...
                            #nan = none..

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [20]:
#df.rename(columns={'Order Id':'order_id','Order Date':'order_date','Ship Mode':'ship_mode'}) 
# there is more pro way
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [21]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [22]:
df['discount']=df['list_price']*df['discount_percent']/100
df.head(10)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3,1.5
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3,0.3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5,45.5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2,0.4
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3,3.3

In [23]:
df['sale_price']=df['list_price']-df['discount']
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0

In [25]:
df['profit'] = df['sale_price'] -df['cost_price']
#if u didn't put equals to what column are u going to add .. it will create a temp colum..it wont change anything.... we have to assign the name with opj
#we use this for not to mess up anything .. like if we alredy assign the value.. what if it could g wrong.. so for double checking purose we need to see the temp data first .. then we can assign the coulm value..
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [26]:
df.drop(columns=['list_price','discount_percent','cost_price'],inplace=True)
#the inplace confirms the changes in the actual data set.. if we didn;t give that .. it wont change anything .. it wil just show u the temp output of the data..

In [31]:
df['order_date']=pd.to_datetime(df['order_date'],format ='%Y-%m-%d')
df.dtypes

order_id                 int64
order_date      datetime64[ns]
ship_mode               object
segment                 object
country                 object
city                    object
state                   object
postal_code              int64
region                  object
category                object
sub_category            object
product_id              object
quantity                 int64
discount               float64
sale_price             float64
profit                 float64
dtype: object

In [36]:
#now we need to connect sql server
import mysql.connector as connection

In [ ]:
engine =connection.create_engin('mysql://')#one way but don't know how

In [37]:
try:
    mydb = connection.connect(host = 'localhost', user = 'root' , password = 'Bhavaaprem', use_pure = True)
    query  = 'Create Database Orders'

    cursor =mydb.cursor()
    cursor.execute(query)
    print(cursor.fetchall())


except Exception as e:
    mydb.close()
    print(str(e))

[]

In [43]:
df.head(10)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,7,1.5,48.5,-1.5
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,4,0.3,9.7,-0.3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,6,45.5,864.5,4.5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,3,0.4,19.6,-0.4
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,5,3.3,106.7,16.7

In [39]:
df.reset_index(drop=True,inplace=True)

In [44]:
df.to_csv('df_orders.csv', index=False)